services:
  rust-server:
    build:
      context: .
      args:
        MOD_FRAMEWORK: ${MOD_FRAMEWORK:-carbon}
      dockerfile: container/Dockerfile

    container_name: rust-server

    ports:
      - "28015:28015/udp"
      - "28016:28016/tcp"

    volumes:
      - type: bind
        source: ./src
        target: ${PLUGIN_PATH:-/srv/rust/carbon/plugins}

    stdin_open: true
    tty: true

    restart: unless-stopped